"""Tables from id Software's Wolfenstein 3D source release, for
tools/extract_assets.py. Generated from the source by
`extract_assets.py --write-tables`; do not edit by hand. The build
parses the source again whenever it is present and checks these agree.

TABLES['WL6'] is Wolfenstein's - the full game's, and the layout the
shareware data really has - and TABLES['SOD'] Spear of Destiny's:

  SOUNDS, MUSIC   the soundnames and musicnames enums in AUDIOWL6.H /
                  AUDIOSOD.H
  DIGIMAP         wolfdigimap[] in WL_MAIN.C, (sound, recording) pairs
  SONGS           songs[] in WL_PLAY.C, a song per floor
  SPRITES         WL_DEF.H's sprite enum, in order
  GRAPHICS        GFXV_WL6.H / GFXV_SOD.H: each graphic's chunk

and for both, LEFTTABLE and RIGHTTABLE, lefttable[] and righttable[] in
WL_GAME.C: the SB Pro stereo attenuations, 15 rows of 30.

id Software's code is used under the GPL grant described in README.md
("License, and what not to redistribute")."""

TABLES = {'LEFTTABLE': [8, 8, 8, 8, 8, 8, 8, 8, 5, 3, 1, 0, 0, 0, 0, 0, 6, 7, 7, 7, 7,
               7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 6, 4, 2, 0,
               0, 0, 0, 0, 4, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 6, 4, 2, 1, 0, 0, 0, 1, 4, 6, 6, 7, 7, 7, 7, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 5, 3, 2, 1, 0, 1,
               2, 4, 5, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 6, 5, 3, 3, 2, 2, 3, 4, 5, 6, 7, 7, 7, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 6, 5, 4, 4, 4, 4, 5, 6,
               6, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 7, 6, 6, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 6, 6, 7, 7, 7, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
               8, 8, 8, 8, 8, 8, 8, 8, 8],
 'RIGHTTABLE': [8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 6, 0, 0, 0, 0, 0, 1, 3,
                5, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7,
                6, 4, 0, 0, 0, 0, 0, 2, 4, 6, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 7, 7, 7, 7, 6, 6, 4, 1, 0, 0, 0, 1, 2, 4, 6, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 6, 5, 4, 2,
                1, 0, 1, 2, 3, 5, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 7, 7, 7, 6, 5, 4, 3, 2, 2, 3, 3, 5, 6, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 6, 6, 5, 4, 4, 4, 4,
                5, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                7, 7, 7, 6, 6, 5, 5, 5, 6, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 6, 6, 7, 7, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
                8, 8, 8, 8, 8, 8, 8, 8, 8],
 'SOD': {'DIGIMAP': [('HALTSND', 0), ('CLOSEDOORSND', 2), ('OPENDOORSND', 3),
                     ('ATKMACHINEGUNSND', 4), ('ATKPISTOLSND', 5),
                     ('ATKGATLINGSND', 6), ('SCHUTZADSND', 7),
                     ('BOSSFIRESND', 8), ('SSFIRESND', 9),
                     ('DEATHSCREAM1SND', 10), ('DEATHSCREAM2SND', 11),
                     ('TAKEDAMAGESND', 12), ('PUSHWALLSND', 13),
                     ('AHHHGSND', 15), ('LEBENSND', 16), ('NAZIFIRESND', 17),
                     ('SLURPIESND', 18), ('LEVELDONESND', 22),
                     ('DEATHSCREAM4SND', 23), ('DEATHSCREAM3SND', 23),
                     ('DEATHSCREAM5SND', 24), ('DEATHSCREAM6SND', 25),
                     ('DEATHSCREAM7SND', 26), ('DEATHSCREAM8SND', 27),
                     ('DEATHSCREAM9SND', 28), ('GETGATLINGSND', 38),
                     ('DOGBARKSND', 1), ('DOGDEATHSND', 14), ('SPIONSND', 19),
                     ('NEINSOVASSND', 20), ('DOGATTACKSND', 21),
                     ('TRANSSIGHTSND', 29), ('TRANSDEATHSND', 30),
                     ('WILHELMSIGHTSND', 31), ('WILHELMDEATHSND', 32),
                     ('UBERDEATHSND', 33), ('KNIGHTSIGHTSND', 34),
                     ('KNIGHTDEATHSND', 35), ('ANGELSIGHTSND', 36),
                     ('ANGELDEATHSND', 37), ('GETSPEARSND', 39)],
         'GRAPHICS': {'BJCOLLAPSE1PIC': 31,
                      'BJCOLLAPSE2PIC': 32,
                      'BJCOLLAPSE3PIC': 33,
                      'BJCOLLAPSE4PIC': 34,
                      'BJOUCHPIC': 147,
                      'BJWAITING1PIC': 145,
                      'BJWAITING2PIC': 146,
                      'BOSSPIC1PIC': 97,
                      'BOSSPIC2PIC': 98,
                      'BOSSPIC3PIC': 99,
                      'BOSSPIC4PIC': 100,
                      'COPYPROTBOXPIC': 96,
                      'COPYPROTTOPPIC': 95,
                      'CREDITSPIC': 92,
                      'C_BABYMODEPIC': 21,
                      'C_BACKDROPPIC': 3,
                      'C_CONTROLPIC': 15,
                      'C_CURSOR1PIC': 5,
                      'C_CURSOR2PIC': 6,
                      'C_CUSTOMIZEPIC': 9,
                      'C_DIGITITLEPIC': 18,
                      'C_DISKLOADING1PIC': 25,
                      'C_DISKLOADING2PIC': 26,
                      'C_EASYPIC': 22,
                      'C_FXTITLEPIC': 17,
                      'C_HARDPIC': 24,
                      'C_HOWTOUGHPIC': 20,
                      'C_JOY1PIC': 10,
                      'C_JOY2PIC': 11,
                      'C_JOYSTICKPIC': 13,
                      'C_KEYBOARDPIC': 14,
                      'C_LOADGAMEPIC': 27,
                      'C_MOUSELBACKPIC': 4,
                      'C_MOUSEPIC': 12,
                      'C_MUSICTITLEPIC': 19,
                      'C_NORMALPIC': 23,
                      'C_NOTSELECTEDPIC': 7,
                      'C_OPTIONSPIC': 16,
                      'C_SAVEGAMEPIC': 28,
                      'C_SELECTEDPIC': 8,
                      'C_WONSPEARPIC': 30,
                      'END1PALETTE': 154,
                      'END2PALETTE': 155,
                      'END3PALETTE': 156,
                      'END4PALETTE': 157,
                      'END5PALETTE': 158,
                      'END6PALETTE': 159,
                      'END7PALETTE': 160,
                      'END8PALETTE': 161,
                      'END9PALETTE': 162,
                      'ENDPICPIC': 35,
                      'ENDSCREEN11PIC': 81,
                      'ENDSCREEN12PIC': 82,
                      'ENDSCREEN3PIC': 83,
                      'ENDSCREEN4PIC': 84,
                      'ENDSCREEN5PIC': 85,
                      'ENDSCREEN6PIC': 86,
                      'ENDSCREEN7PIC': 87,
                      'ENDSCREEN8PIC': 88,
                      'ENDSCREEN9PIC': 89,
                      'ERRORSCREEN': 152,
                      'FACE1APIC': 119,
                      'FACE1BPIC': 120,
                      'FACE1CPIC': 121,
                      'FACE2APIC': 122,
                      'FACE2BPIC': 123,
                      'FACE2CPIC': 124,
                      'FACE3APIC': 125,
                      'FACE3BPIC': 126,
                      'FACE3CPIC': 127,
                      'FACE4APIC': 128,
                      'FACE4BPIC': 129,
                      'FACE4CPIC': 130,
                      'FACE5APIC': 131,
                      'FACE5BPIC': 132,
                      'FACE5CPIC': 133,
                      'FACE6APIC': 134,
                      'FACE6BPIC': 135,
                      'FACE6CPIC': 136,
                      'FACE7APIC': 137,
                      'FACE7BPIC': 138,
                      'FACE7CPIC': 139,
                      'FACE8APIC': 140,
                      'GATLINGGUNPIC': 104,
                      'GETPSYCHEDPIC': 149,
                      'GODMODEFACE1PIC': 142,
                      'GODMODEFACE2PIC': 143,
                      'GODMODEFACE3PIC': 144,
                      'GOLDKEYPIC': 106,
                      'GOTGATLINGPIC': 141,
                      'GUNPIC': 102,
                      'HIGHSCORESPIC': 29,
                      'IDGUYS1PIC': 93,
                      'IDGUYS2PIC': 94,
                      'IDGUYSPALETTE': 163,
                      'KNIFEPIC': 101,
                      'L_APIC': 49,
                      'L_APOSTROPHEPIC': 76,
                      'L_BJWINSPIC': 78,
                      'L_BPIC': 50,
                      'L_COLONPIC': 37,
                      'L_CPIC': 51,
                      'L_DPIC': 52,
                      'L_EPIC': 53,
                      'L_EXPOINTPIC': 75,
                      'L_FPIC': 54,
                      'L_GPIC': 55,
                      'L_GUY2PIC': 77,
                      'L_GUYPIC': 36,
                      'L_HPIC': 56,
                      'L_IPIC': 57,
                      'L_JPIC': 58,
                      'L_KPIC': 59,
                      'L_LPIC': 60,
                      'L_MPIC': 61,
                      'L_NPIC': 62,
                      'L_NUM0PIC': 38,
                      'L_NUM1PIC': 39,
                      'L_NUM2PIC': 40,
                      'L_NUM3PIC': 41,
                      'L_NUM4PIC': 42,
                      'L_NUM5PIC': 43,
                      'L_NUM6PIC': 44,
                      'L_NUM7PIC': 45,
                      'L_NUM8PIC': 46,
                      'L_NUM9PIC': 47,
                      'L_OPIC': 63,
                      'L_PERCENTPIC': 48,
                      'L_PPIC': 64,
                      'L_QPIC': 65,
                      'L_RPIC': 66,
                      'L_SPIC': 67,
                      'L_TPIC': 68,
                      'L_UPIC': 69,
                      'L_VPIC': 70,
                      'L_WPIC': 71,
                      'L_XPIC': 72,
                      'L_YPIC': 73,
                      'L_ZPIC': 74,
                      'MACHINEGUNPIC': 103,
                      'NOKEYPIC': 105,
                      'N_0PIC': 109,
                      'N_1PIC': 110,
                      'N_2PIC': 111,
                      'N_3PIC': 112,
                      'N_4PIC': 113,
                      'N_5PIC': 114,
                      'N_6PIC': 115,
                      'N_7PIC': 116,
                      'N_8PIC': 117,
                      'N_9PIC': 118,
                      'N_BLANKPIC': 108,
                      'ORDERSCREEN': 151,
                      'PAUSEDPIC': 148,
                      'PG13PIC': 91,
                      'SILVERKEYPIC': 107,
                      'STATUSBARPIC': 90,
                      'TITLE1PIC': 79,
                      'TITLE2PIC': 80,
                      'TITLEPALETTE': 153,
                      'T_DEMO0': 164,
                      'T_DEMO1': 165,
                      'T_DEMO2': 166,
                      'T_DEMO3': 167,
                      'T_ENDART1': 168},
         'MUSIC': {'COPYPRO_MUS': 19,
                   'DUNGEON_MUS': 1,
                   'ENDLEVEL_MUS': 16,
                   'GETTHEM_MUS': 3,
                   'GOINGAFT_MUS': 5,
                   'NAZI_OMI_MUS': 8,
                   'POW_MUS': 9,
                   'SEARCHN_MUS': 11,
                   'SUSPENSE_MUS': 12,
                   'TWELFTH_MUS': 10,
                   'ULTIMATE_MUS': 15,
                   'URAHERO_MUS': 6,
                   'WONDERIN_MUS': 14,
                   'XAWARD_MUS': 20,
                   'XDEATH_MUS': 2,
                   'XEVIL_MUS': 17,
                   'XFUNKIE_MUS': 0,
                   'XGETYOU_MUS': 22,
                   'XJAZNAZI_MUS': 18,
                   'XPUTIT_MUS': 21,
                   'XTHEEND_MUS': 7,
                   'XTIPTOE_MUS': 4,
                   'XTOWER2_MUS': 23,
                   'ZEROHOUR_MUS': 13},
         'SONGS': ['XTIPTOE_MUS', 'XFUNKIE_MUS', 'XDEATH_MUS', 'XGETYOU_MUS',
                   'ULTIMATE_MUS', 'DUNGEON_MUS', 'GOINGAFT_MUS', 'POW_MUS',
                   'TWELFTH_MUS', 'ULTIMATE_MUS', 'NAZI_OMI_MUS',
                   'GETTHEM_MUS', 'SUSPENSE_MUS', 'SEARCHN_MUS',
                   'ZEROHOUR_MUS', 'ULTIMATE_MUS', 'XPUTIT_MUS',
                   'ULTIMATE_MUS', 'XJAZNAZI_MUS', 'XFUNKIE_MUS',
                   'XEVIL_MUS'],
         'SOUNDS': {'AHHHGSND': 52,
                    'ANGELDEATHSND': 77,
                    'ANGELFIRESND': 69,
                    'ANGELSIGHTSND': 65,
                    'ANGELTIREDSND': 80,
                    'ATKGATLINGSND': 11,
                    'ATKKNIFESND': 23,
                    'ATKMACHINEGUNSND': 26,
                    'ATKPISTOLSND': 24,
                    'BONUS1SND': 35,
                    'BONUS1UPSND': 44,
                    'BONUS2SND': 36,
                    'BONUS3SND': 37,
                    'BONUS4SND': 45,
                    'BOSSACTIVESND': 49,
                    'BOSSFIRESND': 59,
                    'CLOSEDOORSND': 19,
                    'DEATHSCREAM1SND': 29,
                    'DEATHSCREAM2SND': 22,
                    'DEATHSCREAM3SND': 25,
                    'DEATHSCREAM4SND': 50,
                    'DEATHSCREAM5SND': 53,
                    'DEATHSCREAM6SND': 57,
                    'DEATHSCREAM7SND': 54,
                    'DEATHSCREAM8SND': 55,
                    'DEATHSCREAM9SND': 63,
                    'DOGATTACKSND': 68,
                    'DOGBARKSND': 41,
                    'DOGDEATHSND': 10,
                    'DONOTHINGSND': 20,
                    'ENDBONUS1SND': 42,
                    'ENDBONUS2SND': 43,
                    'ESCPRESSEDSND': 39,
                    'GAMEOVERSND': 17,
                    'GETAMMOBOXSND': 64,
                    'GETAMMOSND': 31,
                    'GETGATLINGSND': 38,
                    'GETKEYSND': 12,
                    'GETMACHINESND': 30,
                    'GETSPEARSND': 79,
                    'GHOSTFADESND': 62,
                    'GHOSTSIGHTSND': 3,
                    'HALTSND': 21,
                    'HEALTH1SND': 33,
                    'HEALTH2SND': 34,
                    'HITENEMYSND': 27,
                    'HITWALLSND': 0,
                    'KNIGHTDEATHSND': 76,
                    'KNIGHTMISSILESND': 78,
                    'KNIGHTSIGHTSND': 75,
                    'LEBENSND': 56,
                    'LEVELDONESND': 40,
                    'MISSILEFIRESND': 8,
                    'MISSILEHITSND': 1,
                    'MOVEGUN1SND': 5,
                    'MOVEGUN2SND': 4,
                    'NAZIFIRESND': 58,
                    'NAZIHITPLAYERSND': 7,
                    'NEINSOVASSND': 67,
                    'NOBONUSSND': 47,
                    'NOITEMSND': 13,
                    'NOWAYSND': 6,
                    'OPENDOORSND': 18,
                    'PERCENT100SND': 48,
                    'PLAYERDEATHSND': 9,
                    'PUSHWALLSND': 46,
                    'SCHUTZADSND': 51,
                    'SELECTITEMSND': 2,
                    'SHOOTDOORSND': 28,
                    'SHOOTSND': 32,
                    'SLURPIESND': 61,
                    'SPIONSND': 66,
                    'SSFIRESND': 60,
                    'TAKEDAMAGESND': 16,
                    'TRANSDEATHSND': 71,
                    'TRANSSIGHTSND': 70,
                    'UBERDEATHSND': 74,
                    'WALK1SND': 14,
                    'WALK2SND': 15,
                    'WILHELMDEATHSND': 73,
                    'WILHELMSIGHTSND': 72},
         'SPRITES': ['SPR_DEMO', 'SPR_DEATHCAM', 'SPR_STAT_0', 'SPR_STAT_1',
                     'SPR_STAT_2', 'SPR_STAT_3', 'SPR_STAT_4', 'SPR_STAT_5',
                     'SPR_STAT_6', 'SPR_STAT_7', 'SPR_STAT_8', 'SPR_STAT_9',
                     'SPR_STAT_10', 'SPR_STAT_11', 'SPR_STAT_12',
                     'SPR_STAT_13', 'SPR_STAT_14', 'SPR_STAT_15',
                     'SPR_STAT_16', 'SPR_STAT_17', 'SPR_STAT_18',
                     'SPR_STAT_19', 'SPR_STAT_20', 'SPR_STAT_21',
                     'SPR_STAT_22', 'SPR_STAT_23', 'SPR_STAT_24',
                     'SPR_STAT_25', 'SPR_STAT_26', 'SPR_STAT_27',
                     'SPR_STAT_28', 'SPR_STAT_29', 'SPR_STAT_30',
                     'SPR_STAT_31', 'SPR_STAT_32', 'SPR_STAT_33',
                     'SPR_STAT_34', 'SPR_STAT_35', 'SPR_STAT_36',
                     'SPR_STAT_37', 'SPR_STAT_38', 'SPR_STAT_39',
                     'SPR_STAT_40', 'SPR_STAT_41', 'SPR_STAT_42',
                     'SPR_STAT_43', 'SPR_STAT_44', 'SPR_STAT_45',
                     'SPR_STAT_46', 'SPR_STAT_47', 'SPR_STAT_48',
                     'SPR_STAT_49', 'SPR_STAT_50', 'SPR_STAT_51',
                     'SPR_GRD_S_1', 'SPR_GRD_S_2', 'SPR_GRD_S_3',
                     'SPR_GRD_S_4', 'SPR_GRD_S_5', 'SPR_GRD_S_6',
                     'SPR_GRD_S_7', 'SPR_GRD_S_8', 'SPR_GRD_W1_1',
                     'SPR_GRD_W1_2', 'SPR_GRD_W1_3', 'SPR_GRD_W1_4',
                     'SPR_GRD_W1_5', 'SPR_GRD_W1_6', 'SPR_GRD_W1_7',
                     'SPR_GRD_W1_8', 'SPR_GRD_W2_1', 'SPR_GRD_W2_2',
                     'SPR_GRD_W2_3', 'SPR_GRD_W2_4', 'SPR_GRD_W2_5',
                     'SPR_GRD_W2_6', 'SPR_GRD_W2_7', 'SPR_GRD_W2_8',
                     'SPR_GRD_W3_1', 'SPR_GRD_W3_2', 'SPR_GRD_W3_3',
                     'SPR_GRD_W3_4', 'SPR_GRD_W3_5', 'SPR_GRD_W3_6',
                     'SPR_GRD_W3_7', 'SPR_GRD_W3_8', 'SPR_GRD_W4_1',
                     'SPR_GRD_W4_2', 'SPR_GRD_W4_3', 'SPR_GRD_W4_4',
                     'SPR_GRD_W4_5', 'SPR_GRD_W4_6', 'SPR_GRD_W4_7',
                     'SPR_GRD_W4_8', 'SPR_GRD_PAIN_1', 'SPR_GRD_DIE_1',
                     'SPR_GRD_DIE_2', 'SPR_GRD_DIE_3', 'SPR_GRD_PAIN_2',
                     'SPR_GRD_DEAD', 'SPR_GRD_SHOOT1', 'SPR_GRD_SHOOT2',
                     'SPR_GRD_SHOOT3', 'SPR_DOG_W1_1', 'SPR_DOG_W1_2',
                     'SPR_DOG_W1_3', 'SPR_DOG_W1_4', 'SPR_DOG_W1_5',
                     'SPR_DOG_W1_6', 'SPR_DOG_W1_7', 'SPR_DOG_W1_8',
                     'SPR_DOG_W2_1', 'SPR_DOG_W2_2', 'SPR_DOG_W2_3',
                     'SPR_DOG_W2_4', 'SPR_DOG_W2_5', 'SPR_DOG_W2_6',
                     'SPR_DOG_W2_7', 'SPR_DOG_W2_8', 'SPR_DOG_W3_1',
                     'SPR_DOG_W3_2', 'SPR_DOG_W3_3', 'SPR_DOG_W3_4',
                     'SPR_DOG_W3_5', 'SPR_DOG_W3_6', 'SPR_DOG_W3_7',
                     'SPR_DOG_W3_8', 'SPR_DOG_W4_1', 'SPR_DOG_W4_2',
                     'SPR_DOG_W4_3', 'SPR_DOG_W4_4', 'SPR_DOG_W4_5',
                     'SPR_DOG_W4_6', 'SPR_DOG_W4_7', 'SPR_DOG_W4_8',
                     'SPR_DOG_DIE_1', 'SPR_DOG_DIE_2', 'SPR_DOG_DIE_3',
                     'SPR_DOG_DEAD', 'SPR_DOG_JUMP1', 'SPR_DOG_JUMP2',
                     'SPR_DOG_JUMP3', 'SPR_SS_S_1', 'SPR_SS_S_2',
                     'SPR_SS_S_3', 'SPR_SS_S_4', 'SPR_SS_S_5', 'SPR_SS_S_6',
                     'SPR_SS_S_7', 'SPR_SS_S_8', 'SPR_SS_W1_1', 'SPR_SS_W1_2',
                     'SPR_SS_W1_3', 'SPR_SS_W1_4', 'SPR_SS_W1_5',
                     'SPR_SS_W1_6', 'SPR_SS_W1_7', 'SPR_SS_W1_8',
                     'SPR_SS_W2_1', 'SPR_SS_W2_2', 'SPR_SS_W2_3',
                     'SPR_SS_W2_4', 'SPR_SS_W2_5', 'SPR_SS_W2_6',
                     'SPR_SS_W2_7', 'SPR_SS_W2_8', 'SPR_SS_W3_1',
                     'SPR_SS_W3_2', 'SPR_SS_W3_3', 'SPR_SS_W3_4',
                     'SPR_SS_W3_5', 'SPR_SS_W3_6', 'SPR_SS_W3_7',
                     'SPR_SS_W3_8', 'SPR_SS_W4_1', 'SPR_SS_W4_2',
                     'SPR_SS_W4_3', 'SPR_SS_W4_4', 'SPR_SS_W4_5',
                     'SPR_SS_W4_6', 'SPR_SS_W4_7', 'SPR_SS_W4_8',
                     'SPR_SS_PAIN_1', 'SPR_SS_DIE_1', 'SPR_SS_DIE_2',
                     'SPR_SS_DIE_3', 'SPR_SS_PAIN_2', 'SPR_SS_DEAD',
                     'SPR_SS_SHOOT1', 'SPR_SS_SHOOT2', 'SPR_SS_SHOOT3',
                     'SPR_MUT_S_1', 'SPR_MUT_S_2', 'SPR_MUT_S_3',
                     'SPR_MUT_S_4', 'SPR_MUT_S_5', 'SPR_MUT_S_6',
                     'SPR_MUT_S_7', 'SPR_MUT_S_8', 'SPR_MUT_W1_1',
                     'SPR_MUT_W1_2', 'SPR_MUT_W1_3', 'SPR_MUT_W1_4',
                     'SPR_MUT_W1_5', 'SPR_MUT_W1_6', 'SPR_MUT_W1_7',
                     'SPR_MUT_W1_8', 'SPR_MUT_W2_1', 'SPR_MUT_W2_2',
                     'SPR_MUT_W2_3', 'SPR_MUT_W2_4', 'SPR_MUT_W2_5',
                     'SPR_MUT_W2_6', 'SPR_MUT_W2_7', 'SPR_MUT_W2_8',
                     'SPR_MUT_W3_1', 'SPR_MUT_W3_2', 'SPR_MUT_W3_3',
                     'SPR_MUT_W3_4', 'SPR_MUT_W3_5', 'SPR_MUT_W3_6',
                     'SPR_MUT_W3_7', 'SPR_MUT_W3_8', 'SPR_MUT_W4_1',
                     'SPR_MUT_W4_2', 'SPR_MUT_W4_3', 'SPR_MUT_W4_4',
                     'SPR_MUT_W4_5', 'SPR_MUT_W4_6', 'SPR_MUT_W4_7',
                     'SPR_MUT_W4_8', 'SPR_MUT_PAIN_1', 'SPR_MUT_DIE_1',
                     'SPR_MUT_DIE_2', 'SPR_MUT_DIE_3', 'SPR_MUT_PAIN_2',
                     'SPR_MUT_DIE_4', 'SPR_MUT_DEAD', 'SPR_MUT_SHOOT1',
                     'SPR_MUT_SHOOT2', 'SPR_MUT_SHOOT3', 'SPR_MUT_SHOOT4',
                     'SPR_OFC_S_1', 'SPR_OFC_S_2', 'SPR_OFC_S_3',
                     'SPR_OFC_S_4', 'SPR_OFC_S_5', 'SPR_OFC_S_6',
                     'SPR_OFC_S_7', 'SPR_OFC_S_8', 'SPR_OFC_W1_1',
                     'SPR_OFC_W1_2', 'SPR_OFC_W1_3', 'SPR_OFC_W1_4',
                     'SPR_OFC_W1_5', 'SPR_OFC_W1_6', 'SPR_OFC_W1_7',
                     'SPR_OFC_W1_8', 'SPR_OFC_W2_1', 'SPR_OFC_W2_2',
                     'SPR_OFC_W2_3', 'SPR_OFC_W2_4', 'SPR_OFC_W2_5',
                     'SPR_OFC_W2_6', 'SPR_OFC_W2_7', 'SPR_OFC_W2_8',
                     'SPR_OFC_W3_1', 'SPR_OFC_W3_2', 'SPR_OFC_W3_3',
                     'SPR_OFC_W3_4', 'SPR_OFC_W3_5', 'SPR_OFC_W3_6',
                     'SPR_OFC_W3_7', 'SPR_OFC_W3_8', 'SPR_OFC_W4_1',
                     'SPR_OFC_W4_2', 'SPR_OFC_W4_3', 'SPR_OFC_W4_4',
                     'SPR_OFC_W4_5', 'SPR_OFC_W4_6', 'SPR_OFC_W4_7',
                     'SPR_OFC_W4_8', 'SPR_OFC_PAIN_1', 'SPR_OFC_DIE_1',
                     'SPR_OFC_DIE_2', 'SPR_OFC_DIE_3', 'SPR_OFC_PAIN_2',
                     'SPR_OFC_DIE_4', 'SPR_OFC_DEAD', 'SPR_OFC_SHOOT1',
                     'SPR_OFC_SHOOT2', 'SPR_OFC_SHOOT3', 'SPR_ROCKET_1',
                     'SPR_ROCKET_2', 'SPR_ROCKET_3', 'SPR_ROCKET_4',
                     'SPR_ROCKET_5', 'SPR_ROCKET_6', 'SPR_ROCKET_7',
                     'SPR_ROCKET_8', 'SPR_SMOKE_1', 'SPR_SMOKE_2',
                     'SPR_SMOKE_3', 'SPR_SMOKE_4', 'SPR_BOOM_1', 'SPR_BOOM_2',
                     'SPR_BOOM_3', 'SPR_HROCKET_1', 'SPR_HROCKET_2',
                     'SPR_HROCKET_3', 'SPR_HROCKET_4', 'SPR_HROCKET_5',
                     'SPR_HROCKET_6', 'SPR_HROCKET_7', 'SPR_HROCKET_8',
                     'SPR_HSMOKE_1', 'SPR_HSMOKE_2', 'SPR_HSMOKE_3',
                     'SPR_HSMOKE_4', 'SPR_HBOOM_1', 'SPR_HBOOM_2',
                     'SPR_HBOOM_3', 'SPR_SPARK1', 'SPR_SPARK2', 'SPR_SPARK3',
                     'SPR_SPARK4', 'SPR_TRANS_W1', 'SPR_TRANS_W2',
                     'SPR_TRANS_W3', 'SPR_TRANS_W4', 'SPR_TRANS_SHOOT1',
                     'SPR_TRANS_SHOOT2', 'SPR_TRANS_SHOOT3', 'SPR_TRANS_DEAD',
                     'SPR_TRANS_DIE1', 'SPR_TRANS_DIE2', 'SPR_TRANS_DIE3',
                     'SPR_WILL_W1', 'SPR_WILL_W2', 'SPR_WILL_W3',
                     'SPR_WILL_W4', 'SPR_WILL_SHOOT1', 'SPR_WILL_SHOOT2',
                     'SPR_WILL_SHOOT3', 'SPR_WILL_SHOOT4', 'SPR_WILL_DIE1',
                     'SPR_WILL_DIE2', 'SPR_WILL_DIE3', 'SPR_WILL_DEAD',
                     'SPR_UBER_W1', 'SPR_UBER_W2', 'SPR_UBER_W3',
                     'SPR_UBER_W4', 'SPR_UBER_SHOOT1', 'SPR_UBER_SHOOT2',
                     'SPR_UBER_SHOOT3', 'SPR_UBER_SHOOT4', 'SPR_UBER_DIE1',
                     'SPR_UBER_DIE2', 'SPR_UBER_DIE3', 'SPR_UBER_DIE4',
                     'SPR_UBER_DEAD', 'SPR_DEATH_W1', 'SPR_DEATH_W2',
                     'SPR_DEATH_W3', 'SPR_DEATH_W4', 'SPR_DEATH_SHOOT1',
                     'SPR_DEATH_SHOOT2', 'SPR_DEATH_SHOOT3',
                     'SPR_DEATH_SHOOT4', 'SPR_DEATH_DIE1', 'SPR_DEATH_DIE2',
                     'SPR_DEATH_DIE3', 'SPR_DEATH_DIE4', 'SPR_DEATH_DIE5',
                     'SPR_DEATH_DIE6', 'SPR_DEATH_DEAD', 'SPR_SPECTRE_W1',
                     'SPR_SPECTRE_W2', 'SPR_SPECTRE_W3', 'SPR_SPECTRE_W4',
                     'SPR_SPECTRE_F1', 'SPR_SPECTRE_F2', 'SPR_SPECTRE_F3',
                     'SPR_SPECTRE_F4', 'SPR_ANGEL_W1', 'SPR_ANGEL_W2',
                     'SPR_ANGEL_W3', 'SPR_ANGEL_W4', 'SPR_ANGEL_SHOOT1',
                     'SPR_ANGEL_SHOOT2', 'SPR_ANGEL_TIRED1',
                     'SPR_ANGEL_TIRED2', 'SPR_ANGEL_DIE1', 'SPR_ANGEL_DIE2',
                     'SPR_ANGEL_DIE3', 'SPR_ANGEL_DIE4', 'SPR_ANGEL_DIE5',
                     'SPR_ANGEL_DIE6', 'SPR_ANGEL_DIE7', 'SPR_ANGEL_DEAD',
                     'SPR_KNIFEREADY', 'SPR_KNIFEATK1', 'SPR_KNIFEATK2',
                     'SPR_KNIFEATK3', 'SPR_KNIFEATK4', 'SPR_PISTOLREADY',
                     'SPR_PISTOLATK1', 'SPR_PISTOLATK2', 'SPR_PISTOLATK3',
                     'SPR_PISTOLATK4', 'SPR_MACHINEGUNREADY',
                     'SPR_MACHINEGUNATK1', 'SPR_MACHINEGUNATK2',
                     'MACHINEGUNATK3', 'SPR_MACHINEGUNATK4', 'SPR_CHAINREADY',
                     'SPR_CHAINATK1', 'SPR_CHAINATK2', 'SPR_CHAINATK3',
                     'SPR_CHAINATK4']},
 'WL6': {'DIGIMAP': [('HALTSND', 0), ('DOGBARKSND', 1), ('CLOSEDOORSND', 2),
                     ('OPENDOORSND', 3), ('ATKMACHINEGUNSND', 4),
                     ('ATKPISTOLSND', 5), ('ATKGATLINGSND', 6),
                     ('SCHUTZADSND', 7), ('GUTENTAGSND', 8), ('MUTTISND', 9),
                     ('BOSSFIRESND', 10), ('SSFIRESND', 11),
                     ('DEATHSCREAM1SND', 12), ('DEATHSCREAM2SND', 13),
                     ('DEATHSCREAM3SND', 13), ('TAKEDAMAGESND', 14),
                     ('PUSHWALLSND', 15), ('LEBENSND', 20),
                     ('NAZIFIRESND', 21), ('SLURPIESND', 22), ('YEAHSND', 32),
                     ('DOGDEATHSND', 16), ('AHHHGSND', 17), ('DIESND', 18),
                     ('EVASND', 19), ('TOT_HUNDSND', 23), ('MEINGOTTSND', 24),
                     ('SCHABBSHASND', 25), ('HITLERHASND', 26),
                     ('SPIONSND', 27), ('NEINSOVASSND', 28),
                     ('DOGATTACKSND', 29), ('LEVELDONESND', 30),
                     ('MECHSTEPSND', 31), ('SCHEISTSND', 33),
                     ('DEATHSCREAM4SND', 34), ('DEATHSCREAM5SND', 35),
                     ('DONNERSND', 36), ('EINESND', 37), ('ERLAUBENSND', 38),
                     ('DEATHSCREAM6SND', 39), ('DEATHSCREAM7SND', 40),
                     ('DEATHSCREAM8SND', 41), ('DEATHSCREAM9SND', 42),
                     ('KEINSND', 43), ('MEINSND', 44), ('ROSESND', 45)],
         'GRAPHICS': {'CREDITSPIC': 89,
                      'C_BABYMODEPIC': 19,
                      'C_CODEPIC': 36,
                      'C_CONTROLPIC': 26,
                      'C_CURSOR1PIC': 11,
                      'C_CURSOR2PIC': 12,
                      'C_CUSTOMIZEPIC': 27,
                      'C_DIGITITLEPIC': 16,
                      'C_DISKLOADING1PIC': 24,
                      'C_DISKLOADING2PIC': 25,
                      'C_EASYPIC': 20,
                      'C_EPISODE1PIC': 30,
                      'C_EPISODE2PIC': 31,
                      'C_EPISODE3PIC': 32,
                      'C_EPISODE4PIC': 33,
                      'C_EPISODE5PIC': 34,
                      'C_EPISODE6PIC': 35,
                      'C_FXTITLEPIC': 15,
                      'C_HARDPIC': 22,
                      'C_JOY1PIC': 41,
                      'C_JOY2PIC': 42,
                      'C_LEVELPIC': 38,
                      'C_LOADGAMEPIC': 28,
                      'C_LOADSAVEDISKPIC': 23,
                      'C_MOUSELBACKPIC': 18,
                      'C_MUSICTITLEPIC': 17,
                      'C_NAMEPIC': 39,
                      'C_NORMALPIC': 21,
                      'C_NOTSELECTEDPIC': 13,
                      'C_OPTIONSPIC': 10,
                      'C_SAVEGAMEPIC': 29,
                      'C_SCOREPIC': 40,
                      'C_SELECTEDPIC': 14,
                      'C_TIMECODEPIC': 37,
                      'ERRORSCREEN': 137,
                      'FACE1APIC': 109,
                      'FACE1BPIC': 110,
                      'FACE1CPIC': 111,
                      'FACE2APIC': 112,
                      'FACE2BPIC': 113,
                      'FACE2CPIC': 114,
                      'FACE3APIC': 115,
                      'FACE3BPIC': 116,
                      'FACE3CPIC': 117,
                      'FACE4APIC': 118,
                      'FACE4BPIC': 119,
                      'FACE4CPIC': 120,
                      'FACE5APIC': 121,
                      'FACE5BPIC': 122,
                      'FACE5CPIC': 123,
                      'FACE6APIC': 124,
                      'FACE6BPIC': 125,
                      'FACE6CPIC': 126,
                      'FACE7APIC': 127,
                      'FACE7BPIC': 128,
                      'FACE7CPIC': 129,
                      'FACE8APIC': 130,
                      'GATLINGGUNPIC': 94,
                      'GETPSYCHEDPIC': 134,
                      'GOLDKEYPIC': 96,
                      'GOTGATLINGPIC': 131,
                      'GUNPIC': 92,
                      'HIGHSCORESPIC': 90,
                      'H_BJPIC': 3,
                      'H_BLAZEPIC': 5,
                      'H_BOTTOMINFOPIC': 9,
                      'H_CASTLEPIC': 4,
                      'H_LEFTWINDOWPIC': 7,
                      'H_RIGHTWINDOWPIC': 8,
                      'H_TOPWINDOWPIC': 6,
                      'KNIFEPIC': 91,
                      'L_APIC': 56,
                      'L_APOSTROPHEPIC': 83,
                      'L_BJWINSPIC': 85,
                      'L_BPIC': 57,
                      'L_COLONPIC': 44,
                      'L_CPIC': 58,
                      'L_DPIC': 59,
                      'L_EPIC': 60,
                      'L_EXPOINTPIC': 82,
                      'L_FPIC': 61,
                      'L_GPIC': 62,
                      'L_GUY2PIC': 84,
                      'L_GUYPIC': 43,
                      'L_HPIC': 63,
                      'L_IPIC': 64,
                      'L_JPIC': 65,
                      'L_KPIC': 66,
                      'L_LPIC': 67,
                      'L_MPIC': 68,
                      'L_NPIC': 69,
                      'L_NUM0PIC': 45,
                      'L_NUM1PIC': 46,
                      'L_NUM2PIC': 47,
                      'L_NUM3PIC': 48,
                      'L_NUM4PIC': 49,
                      'L_NUM5PIC': 50,
                      'L_NUM6PIC': 51,
                      'L_NUM7PIC': 52,
                      'L_NUM8PIC': 53,
                      'L_NUM9PIC': 54,
                      'L_OPIC': 70,
                      'L_PERCENTPIC': 55,
                      'L_PPIC': 71,
                      'L_QPIC': 72,
                      'L_RPIC': 73,
                      'L_SPIC': 74,
                      'L_TPIC': 75,
                      'L_UPIC': 76,
                      'L_VPIC': 77,
                      'L_WPIC': 78,
                      'L_XPIC': 79,
                      'L_YPIC': 80,
                      'L_ZPIC': 81,
                      'MACHINEGUNPIC': 93,
                      'MUTANTBJPIC': 132,
                      'NOKEYPIC': 95,
                      'N_0PIC': 99,
                      'N_1PIC': 100,
                      'N_2PIC': 101,
                      'N_3PIC': 102,
                      'N_4PIC': 103,
                      'N_5PIC': 104,
                      'N_6PIC': 105,
                      'N_7PIC': 106,
                      'N_8PIC': 107,
                      'N_9PIC': 108,
                      'N_BLANKPIC': 98,
                      'ORDERSCREEN': 136,
                      'PAUSEDPIC': 133,
                      'PG13PIC': 88,
                      'SILVERKEYPIC': 97,
                      'STATUSBARPIC': 86,
                      'TITLEPIC': 87,
                      'T_DEMO0': 139,
                      'T_DEMO1': 140,
                      'T_DEMO2': 141,
                      'T_DEMO3': 142,
                      'T_ENDART1': 143,
                      'T_ENDART2': 144,
                      'T_ENDART3': 145,
                      'T_ENDART4': 146,
                      'T_ENDART5': 147,
                      'T_ENDART6': 148,
                      'T_HELPART': 138},
         'MUSIC': {'CORNER_MUS': 0,
                   'DUNGEON_MUS': 1,
                   'ENDLEVEL_MUS': 16,
                   'FUNKYOU_MUS': 15,
                   'GETTHEM_MUS': 3,
                   'GOINGAFT_MUS': 17,
                   'HEADACHE_MUS': 4,
                   'HITLWLTZ_MUS': 5,
                   'INTROCW3_MUS': 6,
                   'NAZI_NOR_MUS': 7,
                   'NAZI_OMI_MUS': 8,
                   'NAZI_RAP_MUS': 20,
                   'PACMAN_MUS': 26,
                   'POW_MUS': 9,
                   'PREGNANT_MUS': 18,
                   'ROSTER_MUS': 23,
                   'SALUTE_MUS': 10,
                   'SEARCHN_MUS': 11,
                   'SUSPENSE_MUS': 12,
                   'TWELFTH_MUS': 22,
                   'ULTIMATE_MUS': 19,
                   'URAHERO_MUS': 24,
                   'VICMARCH_MUS': 25,
                   'VICTORS_MUS': 13,
                   'WARMARCH_MUS': 2,
                   'WONDERIN_MUS': 14,
                   'ZEROHOUR_MUS': 21},
         'SONGS': ['GETTHEM_MUS', 'SEARCHN_MUS', 'POW_MUS', 'SUSPENSE_MUS',
                   'GETTHEM_MUS', 'SEARCHN_MUS', 'POW_MUS', 'SUSPENSE_MUS',
                   'WARMARCH_MUS', 'CORNER_MUS', 'NAZI_OMI_MUS',
                   'PREGNANT_MUS', 'GOINGAFT_MUS', 'HEADACHE_MUS',
                   'NAZI_OMI_MUS', 'PREGNANT_MUS', 'HEADACHE_MUS',
                   'GOINGAFT_MUS', 'WARMARCH_MUS', 'DUNGEON_MUS',
                   'INTROCW3_MUS', 'NAZI_RAP_MUS', 'TWELFTH_MUS',
                   'ZEROHOUR_MUS', 'INTROCW3_MUS', 'NAZI_RAP_MUS',
                   'TWELFTH_MUS', 'ZEROHOUR_MUS', 'ULTIMATE_MUS',
                   'PACMAN_MUS', 'GETTHEM_MUS', 'SEARCHN_MUS', 'POW_MUS',
                   'SUSPENSE_MUS', 'GETTHEM_MUS', 'SEARCHN_MUS', 'POW_MUS',
                   'SUSPENSE_MUS', 'WARMARCH_MUS', 'CORNER_MUS',
                   'NAZI_OMI_MUS', 'PREGNANT_MUS', 'GOINGAFT_MUS',
                   'HEADACHE_MUS', 'NAZI_OMI_MUS', 'PREGNANT_MUS',
                   'HEADACHE_MUS', 'GOINGAFT_MUS', 'WARMARCH_MUS',
                   'DUNGEON_MUS', 'INTROCW3_MUS', 'NAZI_RAP_MUS',
                   'TWELFTH_MUS', 'ZEROHOUR_MUS', 'INTROCW3_MUS',
                   'NAZI_RAP_MUS', 'TWELFTH_MUS', 'ZEROHOUR_MUS',
                   'ULTIMATE_MUS', 'FUNKYOU_MUS'],
         'SOUNDS': {'AHHHGSND': 52,
                    'ATKGATLINGSND': 11,
                    'ATKKNIFESND': 23,
                    'ATKMACHINEGUNSND': 26,
                    'ATKPISTOLSND': 24,
                    'BONUS1SND': 35,
                    'BONUS1UPSND': 44,
                    'BONUS2SND': 36,
                    'BONUS3SND': 37,
                    'BONUS4SND': 45,
                    'BOSSACTIVESND': 49,
                    'BOSSFIRESND': 59,
                    'CLOSEDOORSND': 19,
                    'DEATHSCREAM1SND': 29,
                    'DEATHSCREAM2SND': 22,
                    'DEATHSCREAM3SND': 25,
                    'DEATHSCREAM4SND': 73,
                    'DEATHSCREAM5SND': 74,
                    'DEATHSCREAM6SND': 75,
                    'DEATHSCREAM7SND': 76,
                    'DEATHSCREAM8SND': 77,
                    'DEATHSCREAM9SND': 78,
                    'DIESND': 53,
                    'DOGATTACKSND': 68,
                    'DOGBARKSND': 41,
                    'DOGDEATHSND': 10,
                    'DONNERSND': 79,
                    'DONOTHINGSND': 20,
                    'EINESND': 80,
                    'ENDBONUS1SND': 42,
                    'ENDBONUS2SND': 43,
                    'ERLAUBENSND': 81,
                    'ESCPRESSEDSND': 39,
                    'EVASND': 54,
                    'FLAMETHROWERSND': 69,
                    'GAMEOVERSND': 17,
                    'GETAMMOSND': 31,
                    'GETGATLINGSND': 38,
                    'GETKEYSND': 12,
                    'GETMACHINESND': 30,
                    'GOOBSSND': 71,
                    'GUTENTAGSND': 55,
                    'HALTSND': 21,
                    'HEALTH1SND': 33,
                    'HEALTH2SND': 34,
                    'HEARTBEATSND': 3,
                    'HITENEMYSND': 27,
                    'HITLERHASND': 65,
                    'HITWALLSND': 0,
                    'KEINSND': 82,
                    'LEBENSND': 56,
                    'LEVELDONESND': 40,
                    'MECHSTEPSND': 70,
                    'MEINGOTTSND': 63,
                    'MEINSND': 83,
                    'MISSILEFIRESND': 85,
                    'MISSILEHITSND': 86,
                    'MOVEGUN1SND': 5,
                    'MOVEGUN2SND': 4,
                    'MUTTISND': 50,
                    'NAZIFIRESND': 58,
                    'NAZIHITPLAYERSND': 7,
                    'NEINSOVASSND': 67,
                    'NOBONUSSND': 47,
                    'NOITEMSND': 13,
                    'NOWAYSND': 6,
                    'OPENDOORSND': 18,
                    'PERCENT100SND': 48,
                    'PLAYERDEATHSND': 9,
                    'PUSHWALLSND': 46,
                    'ROSESND': 84,
                    'SCHABBSHASND': 64,
                    'SCHABBSTHROWSND': 8,
                    'SCHEISTSND': 57,
                    'SCHUTZADSND': 51,
                    'SELECTITEMSND': 2,
                    'SELECTWPNSND': 1,
                    'SHOOTDOORSND': 28,
                    'SHOOTSND': 32,
                    'SLURPIESND': 61,
                    'SPIONSND': 66,
                    'SSFIRESND': 60,
                    'TAKEDAMAGESND': 16,
                    'TOT_HUNDSND': 62,
                    'WALK1SND': 14,
                    'WALK2SND': 15,
                    'YEAHSND': 72},
         'SPRITES': ['SPR_DEMO', 'SPR_DEATHCAM', 'SPR_STAT_0', 'SPR_STAT_1',
                     'SPR_STAT_2', 'SPR_STAT_3', 'SPR_STAT_4', 'SPR_STAT_5',
                     'SPR_STAT_6', 'SPR_STAT_7', 'SPR_STAT_8', 'SPR_STAT_9',
                     'SPR_STAT_10', 'SPR_STAT_11', 'SPR_STAT_12',
                     'SPR_STAT_13', 'SPR_STAT_14', 'SPR_STAT_15',
                     'SPR_STAT_16', 'SPR_STAT_17', 'SPR_STAT_18',
                     'SPR_STAT_19', 'SPR_STAT_20', 'SPR_STAT_21',
                     'SPR_STAT_22', 'SPR_STAT_23', 'SPR_STAT_24',
                     'SPR_STAT_25', 'SPR_STAT_26', 'SPR_STAT_27',
                     'SPR_STAT_28', 'SPR_STAT_29', 'SPR_STAT_30',
                     'SPR_STAT_31', 'SPR_STAT_32', 'SPR_STAT_33',
                     'SPR_STAT_34', 'SPR_STAT_35', 'SPR_STAT_36',
                     'SPR_STAT_37', 'SPR_STAT_38', 'SPR_STAT_39',
                     'SPR_STAT_40', 'SPR_STAT_41', 'SPR_STAT_42',
                     'SPR_STAT_43', 'SPR_STAT_44', 'SPR_STAT_45',
                     'SPR_STAT_46', 'SPR_STAT_47', 'SPR_GRD_S_1',
                     'SPR_GRD_S_2', 'SPR_GRD_S_3', 'SPR_GRD_S_4',
                     'SPR_GRD_S_5', 'SPR_GRD_S_6', 'SPR_GRD_S_7',
                     'SPR_GRD_S_8', 'SPR_GRD_W1_1', 'SPR_GRD_W1_2',
                     'SPR_GRD_W1_3', 'SPR_GRD_W1_4', 'SPR_GRD_W1_5',
                     'SPR_GRD_W1_6', 'SPR_GRD_W1_7', 'SPR_GRD_W1_8',
                     'SPR_GRD_W2_1', 'SPR_GRD_W2_2', 'SPR_GRD_W2_3',
                     'SPR_GRD_W2_4', 'SPR_GRD_W2_5', 'SPR_GRD_W2_6',
                     'SPR_GRD_W2_7', 'SPR_GRD_W2_8', 'SPR_GRD_W3_1',
                     'SPR_GRD_W3_2', 'SPR_GRD_W3_3', 'SPR_GRD_W3_4',
                     'SPR_GRD_W3_5', 'SPR_GRD_W3_6', 'SPR_GRD_W3_7',
                     'SPR_GRD_W3_8', 'SPR_GRD_W4_1', 'SPR_GRD_W4_2',
                     'SPR_GRD_W4_3', 'SPR_GRD_W4_4', 'SPR_GRD_W4_5',
                     'SPR_GRD_W4_6', 'SPR_GRD_W4_7', 'SPR_GRD_W4_8',
                     'SPR_GRD_PAIN_1', 'SPR_GRD_DIE_1', 'SPR_GRD_DIE_2',
                     'SPR_GRD_DIE_3', 'SPR_GRD_PAIN_2', 'SPR_GRD_DEAD',
                     'SPR_GRD_SHOOT1', 'SPR_GRD_SHOOT2', 'SPR_GRD_SHOOT3',
                     'SPR_DOG_W1_1', 'SPR_DOG_W1_2', 'SPR_DOG_W1_3',
                     'SPR_DOG_W1_4', 'SPR_DOG_W1_5', 'SPR_DOG_W1_6',
                     'SPR_DOG_W1_7', 'SPR_DOG_W1_8', 'SPR_DOG_W2_1',
                     'SPR_DOG_W2_2', 'SPR_DOG_W2_3', 'SPR_DOG_W2_4',
                     'SPR_DOG_W2_5', 'SPR_DOG_W2_6', 'SPR_DOG_W2_7',
                     'SPR_DOG_W2_8', 'SPR_DOG_W3_1', 'SPR_DOG_W3_2',
                     'SPR_DOG_W3_3', 'SPR_DOG_W3_4', 'SPR_DOG_W3_5',
                     'SPR_DOG_W3_6', 'SPR_DOG_W3_7', 'SPR_DOG_W3_8',
                     'SPR_DOG_W4_1', 'SPR_DOG_W4_2', 'SPR_DOG_W4_3',
                     'SPR_DOG_W4_4', 'SPR_DOG_W4_5', 'SPR_DOG_W4_6',
                     'SPR_DOG_W4_7', 'SPR_DOG_W4_8', 'SPR_DOG_DIE_1',
                     'SPR_DOG_DIE_2', 'SPR_DOG_DIE_3', 'SPR_DOG_DEAD',
                     'SPR_DOG_JUMP1', 'SPR_DOG_JUMP2', 'SPR_DOG_JUMP3',
                     'SPR_SS_S_1', 'SPR_SS_S_2', 'SPR_SS_S_3', 'SPR_SS_S_4',
                     'SPR_SS_S_5', 'SPR_SS_S_6', 'SPR_SS_S_7', 'SPR_SS_S_8',
                     'SPR_SS_W1_1', 'SPR_SS_W1_2', 'SPR_SS_W1_3',
                     'SPR_SS_W1_4', 'SPR_SS_W1_5', 'SPR_SS_W1_6',
                     'SPR_SS_W1_7', 'SPR_SS_W1_8', 'SPR_SS_W2_1',
                     'SPR_SS_W2_2', 'SPR_SS_W2_3', 'SPR_SS_W2_4',
                     'SPR_SS_W2_5', 'SPR_SS_W2_6', 'SPR_SS_W2_7',
                     'SPR_SS_W2_8', 'SPR_SS_W3_1', 'SPR_SS_W3_2',
                     'SPR_SS_W3_3', 'SPR_SS_W3_4', 'SPR_SS_W3_5',
                     'SPR_SS_W3_6', 'SPR_SS_W3_7', 'SPR_SS_W3_8',
                     'SPR_SS_W4_1', 'SPR_SS_W4_2', 'SPR_SS_W4_3',
                     'SPR_SS_W4_4', 'SPR_SS_W4_5', 'SPR_SS_W4_6',
                     'SPR_SS_W4_7', 'SPR_SS_W4_8', 'SPR_SS_PAIN_1',
                     'SPR_SS_DIE_1', 'SPR_SS_DIE_2', 'SPR_SS_DIE_3',
                     'SPR_SS_PAIN_2', 'SPR_SS_DEAD', 'SPR_SS_SHOOT1',
                     'SPR_SS_SHOOT2', 'SPR_SS_SHOOT3', 'SPR_MUT_S_1',
                     'SPR_MUT_S_2', 'SPR_MUT_S_3', 'SPR_MUT_S_4',
                     'SPR_MUT_S_5', 'SPR_MUT_S_6', 'SPR_MUT_S_7',
                     'SPR_MUT_S_8', 'SPR_MUT_W1_1', 'SPR_MUT_W1_2',
                     'SPR_MUT_W1_3', 'SPR_MUT_W1_4', 'SPR_MUT_W1_5',
                     'SPR_MUT_W1_6', 'SPR_MUT_W1_7', 'SPR_MUT_W1_8',
                     'SPR_MUT_W2_1', 'SPR_MUT_W2_2', 'SPR_MUT_W2_3',
                     'SPR_MUT_W2_4', 'SPR_MUT_W2_5', 'SPR_MUT_W2_6',
                     'SPR_MUT_W2_7', 'SPR_MUT_W2_8', 'SPR_MUT_W3_1',
                     'SPR_MUT_W3_2', 'SPR_MUT_W3_3', 'SPR_MUT_W3_4',
                     'SPR_MUT_W3_5', 'SPR_MUT_W3_6', 'SPR_MUT_W3_7',
                     'SPR_MUT_W3_8', 'SPR_MUT_W4_1', 'SPR_MUT_W4_2',
                     'SPR_MUT_W4_3', 'SPR_MUT_W4_4', 'SPR_MUT_W4_5',
                     'SPR_MUT_W4_6', 'SPR_MUT_W4_7', 'SPR_MUT_W4_8',
                     'SPR_MUT_PAIN_1', 'SPR_MUT_DIE_1', 'SPR_MUT_DIE_2',
                     'SPR_MUT_DIE_3', 'SPR_MUT_PAIN_2', 'SPR_MUT_DIE_4',
                     'SPR_MUT_DEAD', 'SPR_MUT_SHOOT1', 'SPR_MUT_SHOOT2',
                     'SPR_MUT_SHOOT3', 'SPR_MUT_SHOOT4', 'SPR_OFC_S_1',
                     'SPR_OFC_S_2', 'SPR_OFC_S_3', 'SPR_OFC_S_4',
                     'SPR_OFC_S_5', 'SPR_OFC_S_6', 'SPR_OFC_S_7',
                     'SPR_OFC_S_8', 'SPR_OFC_W1_1', 'SPR_OFC_W1_2',
                     'SPR_OFC_W1_3', 'SPR_OFC_W1_4', 'SPR_OFC_W1_5',
                     'SPR_OFC_W1_6', 'SPR_OFC_W1_7', 'SPR_OFC_W1_8',
                     'SPR_OFC_W2_1', 'SPR_OFC_W2_2', 'SPR_OFC_W2_3',
                     'SPR_OFC_W2_4', 'SPR_OFC_W2_5', 'SPR_OFC_W2_6',
                     'SPR_OFC_W2_7', 'SPR_OFC_W2_8', 'SPR_OFC_W3_1',
                     'SPR_OFC_W3_2', 'SPR_OFC_W3_3', 'SPR_OFC_W3_4',
                     'SPR_OFC_W3_5', 'SPR_OFC_W3_6', 'SPR_OFC_W3_7',
                     'SPR_OFC_W3_8', 'SPR_OFC_W4_1', 'SPR_OFC_W4_2',
                     'SPR_OFC_W4_3', 'SPR_OFC_W4_4', 'SPR_OFC_W4_5',
                     'SPR_OFC_W4_6', 'SPR_OFC_W4_7', 'SPR_OFC_W4_8',
                     'SPR_OFC_PAIN_1', 'SPR_OFC_DIE_1', 'SPR_OFC_DIE_2',
                     'SPR_OFC_DIE_3', 'SPR_OFC_PAIN_2', 'SPR_OFC_DIE_4',
                     'SPR_OFC_DEAD', 'SPR_OFC_SHOOT1', 'SPR_OFC_SHOOT2',
                     'SPR_OFC_SHOOT3', 'SPR_BLINKY_W1', 'SPR_BLINKY_W2',
                     'SPR_PINKY_W1', 'SPR_PINKY_W2', 'SPR_CLYDE_W1',
                     'SPR_CLYDE_W2', 'SPR_INKY_W1', 'SPR_INKY_W2',
                     'SPR_BOSS_W1', 'SPR_BOSS_W2', 'SPR_BOSS_W3',
                     'SPR_BOSS_W4', 'SPR_BOSS_SHOOT1', 'SPR_BOSS_SHOOT2',
                     'SPR_BOSS_SHOOT3', 'SPR_BOSS_DEAD', 'SPR_BOSS_DIE1',
                     'SPR_BOSS_DIE2', 'SPR_BOSS_DIE3', 'SPR_SCHABB_W1',
                     'SPR_SCHABB_W2', 'SPR_SCHABB_W3', 'SPR_SCHABB_W4',
                     'SPR_SCHABB_SHOOT1', 'SPR_SCHABB_SHOOT2',
                     'SPR_SCHABB_DIE1', 'SPR_SCHABB_DIE2', 'SPR_SCHABB_DIE3',
                     'SPR_SCHABB_DEAD', 'SPR_HYPO1', 'SPR_HYPO2', 'SPR_HYPO3',
                     'SPR_HYPO4', 'SPR_FAKE_W1', 'SPR_FAKE_W2', 'SPR_FAKE_W3',
                     'SPR_FAKE_W4', 'SPR_FAKE_SHOOT', 'SPR_FIRE1',
                     'SPR_FIRE2', 'SPR_FAKE_DIE1', 'SPR_FAKE_DIE2',
                     'SPR_FAKE_DIE3', 'SPR_FAKE_DIE4', 'SPR_FAKE_DIE5',
                     'SPR_FAKE_DEAD', 'SPR_MECHA_W1', 'SPR_MECHA_W2',
                     'SPR_MECHA_W3', 'SPR_MECHA_W4', 'SPR_MECHA_SHOOT1',
                     'SPR_MECHA_SHOOT2', 'SPR_MECHA_SHOOT3', 'SPR_MECHA_DEAD',
                     'SPR_MECHA_DIE1', 'SPR_MECHA_DIE2', 'SPR_MECHA_DIE3',
                     'SPR_HITLER_W1', 'SPR_HITLER_W2', 'SPR_HITLER_W3',
                     'SPR_HITLER_W4', 'SPR_HITLER_SHOOT1',
                     'SPR_HITLER_SHOOT2', 'SPR_HITLER_SHOOT3',
                     'SPR_HITLER_DEAD', 'SPR_HITLER_DIE1', 'SPR_HITLER_DIE2',
                     'SPR_HITLER_DIE3', 'SPR_HITLER_DIE4', 'SPR_HITLER_DIE5',
                     'SPR_HITLER_DIE6', 'SPR_HITLER_DIE7', 'SPR_GIFT_W1',
                     'SPR_GIFT_W2', 'SPR_GIFT_W3', 'SPR_GIFT_W4',
                     'SPR_GIFT_SHOOT1', 'SPR_GIFT_SHOOT2', 'SPR_GIFT_DIE1',
                     'SPR_GIFT_DIE2', 'SPR_GIFT_DIE3', 'SPR_GIFT_DEAD',
                     'SPR_ROCKET_1', 'SPR_ROCKET_2', 'SPR_ROCKET_3',
                     'SPR_ROCKET_4', 'SPR_ROCKET_5', 'SPR_ROCKET_6',
                     'SPR_ROCKET_7', 'SPR_ROCKET_8', 'SPR_SMOKE_1',
                     'SPR_SMOKE_2', 'SPR_SMOKE_3', 'SPR_SMOKE_4',
                     'SPR_BOOM_1', 'SPR_BOOM_2', 'SPR_BOOM_3',
                     'SPR_GRETEL_W1', 'SPR_GRETEL_W2', 'SPR_GRETEL_W3',
                     'SPR_GRETEL_W4', 'SPR_GRETEL_SHOOT1',
                     'SPR_GRETEL_SHOOT2', 'SPR_GRETEL_SHOOT3',
                     'SPR_GRETEL_DEAD', 'SPR_GRETEL_DIE1', 'SPR_GRETEL_DIE2',
                     'SPR_GRETEL_DIE3', 'SPR_FAT_W1', 'SPR_FAT_W2',
                     'SPR_FAT_W3', 'SPR_FAT_W4', 'SPR_FAT_SHOOT1',
                     'SPR_FAT_SHOOT2', 'SPR_FAT_SHOOT3', 'SPR_FAT_SHOOT4',
                     'SPR_FAT_DIE1', 'SPR_FAT_DIE2', 'SPR_FAT_DIE3',
                     'SPR_FAT_DEAD', 'SPR_BJ_W1', 'SPR_BJ_W2', 'SPR_BJ_W3',
                     'SPR_BJ_W4', 'SPR_BJ_JUMP1', 'SPR_BJ_JUMP2',
                     'SPR_BJ_JUMP3', 'SPR_BJ_JUMP4', 'SPR_KNIFEREADY',
                     'SPR_KNIFEATK1', 'SPR_KNIFEATK2', 'SPR_KNIFEATK3',
                     'SPR_KNIFEATK4', 'SPR_PISTOLREADY', 'SPR_PISTOLATK1',
                     'SPR_PISTOLATK2', 'SPR_PISTOLATK3', 'SPR_PISTOLATK4',
                     'SPR_MACHINEGUNREADY', 'SPR_MACHINEGUNATK1',
                     'SPR_MACHINEGUNATK2', 'MACHINEGUNATK3',
                     'SPR_MACHINEGUNATK4', 'SPR_CHAINREADY', 'SPR_CHAINATK1',
                     'SPR_CHAINATK2', 'SPR_CHAINATK3', 'SPR_CHAINATK4']}}
